import type { WebApp, PlatformConnection, Content, AnalyticsSummary, PricingPlan, Platform } from '@/types';

export const mockUser = {
  id: 'user-1',
  email: 'demo@amarktai.com',
  name: 'Demo User',
  plan: 'pro' as const,
  createdAt: '2024-01-01T00:00:00Z',
};

export const mockWebApps: WebApp[] = [
  {
    id: 'webapp-1',
    userId: 'user-1',
    name: 'TaskFlow Pro',
    url: 'https://taskflowpro.com',
    description: 'AI-powered project management tool for remote teams',
    category: 'SaaS',
    targetAudience: 'Remote teams, project managers, startups',
    keyFeatures: ['AI task prioritization', 'Time tracking', 'Team collaboration', 'Automated reporting'],
    isActive: true,
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z',
  },
  {
    id: 'webapp-2',
    userId: 'user-1',
    name: 'CodeSnippet Library',
    url: 'https://codesnippet.dev',
    description: 'Organize and share your code snippets with your team',
    category: 'Developer Tools',
    targetAudience: 'Software developers, engineering teams',
    keyFeatures: ['Syntax highlighting', 'Team sharing', 'VS Code extension', 'Cloud sync'],
    isActive: true,
    createdAt: '2024-02-01T00:00:00Z',
    updatedAt: '2024-02-01T00:00:00Z',
  },
];

export const mockPlatformConnections: PlatformConnection[] = [
  { id: 'conn-1', userId: 'user-1', platform: 'youtube', accountName: 'Demo Channel', accountId: 'yt-123', isActive: true, connectedAt: '2024-01-10T00:00:00Z' },
  { id: 'conn-2', userId: 'user-1', platform: 'tiktok', accountName: '@demouser', accountId: 'tt-456', isActive: true, connectedAt: '2024-01-12T00:00:00Z' },
  { id: 'conn-3', userId: 'user-1', platform: 'instagram', accountName: '@demouser', accountId: 'ig-789', isActive: true, connectedAt: '2024-01-15T00:00:00Z' },
  { id: 'conn-4', userId: 'user-1', platform: 'twitter', accountName: '@demouser', accountId: 'tw-abc', isActive: true, connectedAt: '2024-01-20T00:00:00Z' },
];

export const mockContent: Content[] = [
  {
    id: 'content-1',
    userId: 'user-1',
    webappId: 'webapp-1',
    platform: 'youtube',
    type: 'video',
    status: 'posted',
    title: 'How AI Transforms Project Management',
    caption: 'Discover how AI can automate your project management workflow and save 10+ hours per week! 🚀\n\n#ProjectManagement #AI #Productivity #RemoteWork',
    hashtags: ['ProjectManagement', 'AI', 'Productivity', 'RemoteWork'],
    mediaUrls: ['https://images.unsplash.com/photo-1552664730-d307ca884978?w=800'],
    scheduledFor: '2024-02-01T10:00:00Z',
    postedAt: '2024-02-01T10:00:00Z',
    performance: { views: 1250, likes: 89, comments: 12, shares: 23, clicks: 156, ctr: 12.5 },
    createdAt: '2024-01-31T00:00:00Z',
    updatedAt: '2024-02-01T10:00:00Z',
  },
  {
    id: 'content-2',
    userId: 'user-1',
    webappId: 'webapp-1',
    platform: 'instagram',
    type: 'image',
    status: 'approved',
    title: '5 Tips for Remote Team Collaboration',
    caption: 'Remote work doesn\'t have to be isolating. Here are 5 proven strategies to keep your team connected and productive! 💪\n\nWhich tip resonates with you most? Comment below! 👇',
    hashtags: ['RemoteWork', 'TeamCollaboration', 'ProductivityTips', 'WorkFromHome'],
    mediaUrls: ['https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=800'],
    scheduledFor: '2024-02-05T14:00:00Z',
    createdAt: '2024-02-04T00:00:00Z',
    updatedAt: '2024-02-04T00:00:00Z',
  },
  {
    id: 'content-3',
    userId: 'user-1',
    webappId: 'webapp-2',
    platform: 'twitter',
    type: 'text',
    status: 'pending',
    title: 'Code Organization Tip',
    caption: '💡 Pro tip: Spend 10 minutes organizing your code snippets today, save hours searching tomorrow.\n\nA well-organized snippet library = faster development = more time for innovation 🚀\n\nHow do you organize your code?',
    hashtags: ['CodeOrganization', 'DeveloperTips', 'Programming'],
    mediaUrls: [],
    createdAt: '2024-02-05T00:00:00Z',
    updatedAt: '2024-02-05T00:00:00Z',
  },
  {
    id: 'content-4',
    userId: 'user-1',
    webappId: 'webapp-1',
    platform: 'tiktok',
    type: 'video',
    status: 'pending',
    title: 'POV: You Discovered AI Task Management',
    caption: 'When you realize AI can prioritize your tasks better than you can 😅\n\n#AITools #ProductivityHacks #WorkSmarter #TaskManagement',
    hashtags: ['AITools', 'ProductivityHacks', 'WorkSmarter', 'TaskManagement'],
    mediaUrls: ['https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800'],
    createdAt: '2024-02-05T00:00:00Z',
    updatedAt: '2024-02-05T00:00:00Z',
  },
  {
    id: 'content-5',
    userId: 'user-1',
    webappId: 'webapp-2',
    platform: 'linkedin',
    type: 'image',
    status: 'pending',
    title: 'The Future of Code Sharing',
    caption: 'As engineering teams grow, code sharing becomes critical for maintaining consistency and speed.\n\nThe teams that invest in proper snippet management see:\n✅ 40% faster onboarding\n✅ 30% reduction in bugs\n✅ 25% increase in developer satisfaction\n\nWhat\'s your approach to code sharing within your team?',
    hashtags: ['EngineeringManagement', 'CodeQuality', 'DevTools', 'SoftwareDevelopment'],
    mediaUrls: ['https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800'],
    createdAt: '2024-02-05T00:00:00Z',
    updatedAt: '2024-02-05T00:00:00Z',
  },
];

export const mockAnalytics: AnalyticsSummary = {
  totalPosts: 47,
  totalViews: 28500,
  totalEngagement: 3420,
  avgCtr: 8.7,
  platformBreakdown: {
    youtube: { posts: 8, views: 8500, engagement: 680, ctr: 10.2 },
    tiktok: { posts: 12, views: 12000, engagement: 1560, ctr: 7.5 },
    instagram: { posts: 10, views: 4200, engagement: 680, ctr: 9.1 },
    facebook: { posts: 5, views: 1800, engagement: 220, ctr: 6.8 },
    twitter: { posts: 8, views: 1200, engagement: 180, ctr: 11.5 },
    linkedin: { posts: 4, views: 800, engagement: 100, ctr: 12.8 },
    pinterest: { posts: 0, views: 0, engagement: 0, ctr: 0 },
    reddit: { posts: 0, views: 0, engagement: 0, ctr: 0 },
    bluesky: { posts: 0, views: 0, engagement: 0, ctr: 0 },
    threads: { posts: 0, views: 0, engagement: 0, ctr: 0 },
    telegram: { posts: 0, views: 0, engagement: 0, ctr: 0 },
    snapchat: { posts: 0, views: 0, engagement: 0, ctr: 0 },
  },
  dailyStats: [
    { date: '2024-01-30', posts: 2, views: 1200, engagement: 145 },
    { date: '2024-01-31', posts: 1, views: 800, engagement: 98 },
    { date: '2024-02-01', posts: 3, views: 2100, engagement: 267 },
    { date: '2024-02-02', posts: 2, views: 1500, engagement: 189 },
    { date: '2024-02-03', posts: 1, views: 900, engagement: 112 },
    { date: '2024-02-04', posts: 2, views: 1800, engagement: 234 },
    { date: '2024-02-05', posts: 3, views: 2400, engagement: 298 },
  ],
};

export const pricingPlans: PricingPlan[] = [
  {
    id: 'free',
    name: 'Free',
    price: 0,
    description: 'Perfect for getting started',
    features: [
      '1 Web App',
      '3 Social Platforms',
      '3 posts per day',
      'Basic AI content generation',
      'Standard analytics',
      'Community support',
    ],
    limits: {
      webapps: 1,
      platforms: 3,
      postsPerDay: 3,
      imagesPerMonth: 30,
      videosPerMonth: 5,
    },
  },
  {
    id: 'pro',
    name: 'Pro',
    price: 29,
    description: 'Best for growing businesses',
    features: [
      '5 Web Apps',
      'All 6 Platforms',
      '12 posts per day',
      'Advanced AI with Grok/Claude',
      'A/B testing & optimization',
      'Priority email support',
      'Hashtag research',
    ],
    limits: {
      webapps: 5,
      platforms: 6,
      postsPerDay: 12,
      imagesPerMonth: 150,
      videosPerMonth: 30,
    },
    highlighted: true,
  },
  {
    id: 'business',
    name: 'Business',
    price: 99,
    description: 'For teams and agencies',
    features: [
      'Unlimited Web Apps',
      'All 6 Platforms',
      '36 posts per day',
      'Premium AI with GPT-4o',
      'Team collaboration (5 seats)',
      'Dedicated support',
      'Custom workflows',
      'White-label options',
    ],
    limits: {
      webapps: -1,
      platforms: 6,
      postsPerDay: 36,
      imagesPerMonth: 500,
      videosPerMonth: 100,
    },
  },
];

export const platformInfo: Record<Platform, { name: string; icon: string; color: string; description: string }> = {
  youtube: {
    name: 'YouTube Shorts',
    icon: 'Youtube',
    color: '#FF0000',
    description: 'Short-form video content for maximum reach',
  },
  tiktok: {
    name: 'TikTok',
    icon: 'Music',
    color: '#000000',
    description: 'Viral short videos for Gen Z and millennials',
  },
  instagram: {
    name: 'Instagram',
    icon: 'Instagram',
    color: '#E4405F',
    description: 'Reels and posts for visual storytelling',
  },
  facebook: {
    name: 'Facebook',
    icon: 'Facebook',
    color: '#1877F2',
    description: 'Reels and posts for broad demographic reach',
  },
  twitter: {
    name: 'X (Twitter)',
    icon: 'Twitter',
    color: '#000000',
    description: 'Short posts and threads for tech audiences',
  },
  linkedin: {
    name: 'LinkedIn',
    icon: 'Linkedin',
    color: '#0A66C2',
    description: 'Professional content for B2B marketing',
  },
  pinterest: {
    name: 'Pinterest',
    icon: 'Pin',
    color: '#E60023',
    description: 'Visual discovery engine for inspiration and shopping',
  },
  reddit: {
    name: 'Reddit',
    icon: 'MessageCircle',
    color: '#FF4500',
    description: 'Community-driven discussions and niche audiences',
  },
  bluesky: {
    name: 'Bluesky',
    icon: 'CloudSun',
    color: '#0085FF',
    description: 'Decentralised social network growing rapidly',
  },
  threads: {
    name: 'Threads',
    icon: 'AtSign',
    color: '#000000',
    description: 'Meta\'s text-based conversation platform',
  },
  telegram: {
    name: 'Telegram',
    icon: 'Send',
    color: '#26A5E4',
    description: 'Broadcast to engaged channel subscribers',
  },
  snapchat: {
    name: 'Snapchat',
    icon: 'Ghost',
    color: '#FFFC00',
    description: 'Ephemeral content for younger audiences',
  },
};
